{% set version = "1.1.4" %}
{% set name = "cypari2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/defeo/cypari2/archive/{{ version }}.tar.gz
  sha256: b61e30a697250adf6369c21f148f7552aae6abfbb673171c2b97ec3c8fb74676

build:
  number: 2
  skip: true  # [win]
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - cython
    - python
    - pari >=2.9
    - pip
    - cysignals
  run:
    - python
    - {{ pin_compatible('pari', max_pin='x.x.x') }}
    - cysignals

test:
  imports:
    - cypari2
  commands:
    - python -c "import doctest; import cypari2; doctest.testmod(cypari2, optionflags=doctest.ELLIPSIS|doctest.REPORT_NDIFF)"
    - test -f $SP_DIR/cypari2/auto_paridecl.pxd

about:
  home: https://github.com/defeo/cypari2
  license: GPLv2+
  license_file: LICENSE
  summary: 'An interface to the number theory library libpari'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
