travis:
  secure:
    BINSTAR_TOKEN: P6rqign7+QZ928deRL2iLtU6qpLcIMLeZJF1d7IU+ioCdCDMV8DF7kgEz2+RlAowKTmndeariV1Blx4/bi8V0X2mEwrlzHYXlXKwEPIj11aiRD8bPpfapoTF5h1vJ+UNI6qiNEf/es2xKDbPzsS3xBZ/2JPPFy/xG9HemuCviC20I3PBcQP7ycqk1sDMuV9PliM/lDpBrUtcznlAL7ymhZKhQkA8QJ0KoDlUTmoR3Z6nKlPgT3wd//PI0ofA2cdeledKfFSMPeD0Gd2NT5UhBtVylYEAOWezeqratSM0SG6I//g0T5lfH3frZQmwU3FJiuy46ZSilVlMRJCH2yLngQgkEuJeWBerx9xKj1tI8JHQkLK/X3y1EafWfy2Zy7n7vpZwSfdyoTuG/gN9CiGpOkjdo2BucFUo+hsEHNZUuS1qStUosy3NBarnOVl0mKbJ44z32fyiG9r/JC3fA9DS7qR660zBGKYas3eLsZYEtnoBqc0xVl8KbnXKl9flMVyBOoj5iBqbWUlHVO+SD6GyKycuzs/a3k2+86Szyv4gQAUcEn58AKAWaxu+dxMFKRl6w9xaFK4Cyzp2rqVeQ72E11sqE98pyq4XNSWuJnzCHM5yz6Mt5Luv2biCZVKQI9I111safmPiLHXvu9q/wE8F6UKmHfpzMjbEpZ+DzWXnqTg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
